pipeline:
    publish:docker:
        image: plugins/docker
        repo: spartan563/cv
        tag:
            - latest
            - "${DRONE_COMMIT_BRANCH}"
        build_args:
            - "VERSION=${DRONE_COMMIT_SHA}"
        secrets: [ docker_username, docker_password ]

    sentry:release:
      image: sierrasoftworks/drone-sentry
      pull: true
      
      organization: sierrasoftworks
      project: cv

      release: true
      release_version: "${DRONE_COMMIT_SHA}"
      release_url: "${DRONE_COMMIT_LINK}"

      secrets:
        - sentry_server
        - sentry_token

    sentry:deploy:
      image: sierrasoftworks/drone-sentry
      pull: true

      organization: sierrasoftworks
      project: cv

      release_version: "${DRONE_COMMIT_SHA}"

      deploy: true
      deploy_environment: "Docker Hub"
      deploy_name: "spartan563/cv:${DRONE_COMMIT_BRANCH}"
      deploy_url: "https://hub.docker.com/r/spartan563/cv/"

      secrets:
        - sentry_server
        - sentry_token