pipeline:

    npm:install:
        image: node:6.3-slim
        commands:
            - cd app
            - npm install --silent --progress=false

    npm:build:
        image: node:6.3-slim
        commands:
            - cd app
            - npm run build:prod

    docker:
        repo: spartan563/cv
        tag: 
            - latest
            - "${DRONE_COMMIT_BRANCH}"
        username: "${DOCKER_USERNAME}"
        password: "${DOCKER_PASSWORD}"
        email: "${DOCKER_EMAIL}"
        build_args:
            - "VERSION=${DRONE_COMMIT_SHA}"