trigger:
  - master
  
variables:
  tag: 'r$(Build.BuildId)'
  image: spartan563/cv

resources:
  repositories:
    - repository: templates
      type: github
      name: SierraSoftworks/devops-pipelines
      endpoint: SierraSoftworks

extends:
  template: azurecdn/website.yml@templates
  parameters:
    build:
      - job: build_site
        displayName: Build Website
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '12.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
            displayName: 'npm install'

          - script: |
              npm run build
            displayName: 'npm build'

          - publish: ./src/
            artifact: site
      - job: build_docker
        displayName: Build Docker Image
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build Docker Image
            inputs:
              command: buildAndPush
              dockerfile: 'Dockerfile'
              containerRegistry: Docker Hub
              repository: $(image)
              tags: |
                latest
                $(tag)
    pool:
      vmImage: windows-latest
    
    subscription: MSFT Benefit

    # If you've got multiple resource groups, this should match the one used by your CDN profile.
    resourcegroup: app-resume
    cdn_profile: cdn-resume-bpannell

    staging:
      environment: staging-cv-sierrasoftworks-com
      cdn_endpoint: null
      artifact: site
      container: staging
      storage: resumebpannell
      healthcheck: https://resumebpannell.blob.core.windows.net/staging/index.html

    production:
      environment: cv-sierrasoftworks-com
      cdn_endpoint: resumebpannell
      artifact: site
      container: $web
      storage: resumebpannell
      healthcheck: https://cv.sierrasoftworks.com/
