---
- name: enable EPEL repository
  yum: name=epel-release state=present
  
- name: install nginx repo
  template: >
    src=nginx.repo
    dest=/etc/yum.repos.d/nginx.repo
    force=no
#   yumrepo: >
#     baseurl={{nginx_package_url}}
#     enable=yes
#     gpgcheck=no
#     name=nginx
      
- name: install nginx
  yum: name=nginx state=present
  
- name: remove default site entries
  file: "path=/etc/nginx/conf.d/{{item}} state=absent"
  with_items: "{{nginx_default_sites}}"
    
- name: enable firewall ports
  firewalld: "port={{item}} permanent=yes state=enabled immediate=yes"
  with_items: "{{nginx_ports}}"
  
- name: generate dh prime params
  command: "openssl dhparam 2048 -out {{nginx_dhparam}}"
  
- name: start nginx
  service: name=nginx state=running enabled=yes