---
- name: enable EPEL repository
  yum: name=epel-release state=present
  
- name: install nginx repo
  yumrepo: >
    baseurl={{nginx_package_url}}
    enable=yes
    gpgcheck=no
    name=nginx
      
- name: install nginx
  yum: name=nginx state=latest
  
- name: remove default site entries
  file: "path=/etc/nginx/conf.d/{{item}} state=absent"
  with_items: "{{nginx_default_sites}}"
    
- name: enable firewall ports
  firewalld: "port={{item}} permanent=yes state=enabled immediate=yes"
  with_items: "{{nginx_ports}}"
  
- name: start nginx
  service: name=nginx state=running enabled=yes