---
haproxy_ports:
  - 80/tcp
  
haproxy_user: haproxy
haproxy_group: haproxy

haproxy_config: /etc/haproxy/haproxy.conf

haproxy_health_port: 8999
haproxy_health_endpoint: monitor
haproxy_health_realm: Sierra Softworks
haproxy_health_url: "http://localhost/{{haproxy_health_port}}/{{haproxy_health_endpoint}}"
haproxy_health_interval: 30s
haproxy_health_timeout: 10ms

haproxy_consul_name: haproxy
haproxy_consul_tags:
  - primary
haproxy_consul_port: 80