---
- name: create start deploying this version
  deploy_helper: >
    path={{website_deployment_dir}}
    release={{website_version}}

- name: clone latest project version
  git: >
    repo={{website_repo}}
    dest={{deploy_helper.new_release_path}}
    version={{website_version}}
    
- name: install npm modules
  npm: "state=present path={{deploy_helper.new_release_path}}"
  
- name: install jspm packages
  command: "jspm install chdir={{deploy_helper.new_release_path}}"
  
- name: execute gulp bundling step
  command: "gulp bundle chdir={{deploy_helper.new_release_path}}"

- name: rollout the application version
  deploy_helper: >
    current_path={{website_root_dir}}
    path={{website_deployment_dir}}
    release={{deploy_helper.new_release}}
    state=finalize