---
- name: install git
  yum: name=git state=present

- name: create start deploying this version
  deploy_helper: >
    path={{deployment_dir}}
    current_path={{deployment_current_dir}}
    release={{website_version}}

- name: clone latest project version
  git: >
    repo={{website_repo}}
    dest={{deploy_helper.new_release_path}}
    version={{website_version}}
    
- name: install npm modules
  npm: "state=present path={{deploy_helper.new_release_path}}/Frontend"
  
- name: install jspm packages
  command: "{{deploy_helper.new_release_path}}/Frontend/{{deployment_command_path}}/jspm install chdir={{deploy_helper.new_release_path}}/Frontend"
  
- name: execute gulp bundling step
  command: "{{deploy_helper.new_release_path}}/Frontend/{{deployment_command_path}}/gulp bundle chdir={{deploy_helper.new_release_path}}/Frontend"

- name: rollout the application version
  deploy_helper: >
    path={{deployment_dir}}
    current_path={{deployment_current_dir}}
    release={{deploy_helper.new_release}}
    state=finalize