---
- name: install EPEL repository
  yum: name=epel-release state=present
  
- name: create consul group
  group: "name={{consul_group}} state=present"
  
- name: create consul user
  user: "name={{consul_user}} group={{consul_group}} home={{consul_data_dir}} system=yes"
  
- name: create consul directories
  file: "state=directory path={{item}} owner={{consul_user}} group={{consul_group}}"
  with_items:
    - "{{consul_data_dir}}"
    - "{{consul_config_dir}}"
    - "{{consul_install_dir}}"
  
- name: check for existing archive
  stat: "path={{consul_download_dir}}/{{consul_download_file}}"
  register: consul_download_stat
  
- name: download consul
  get_url: >
    url={{consul_download_url}}
    dest={{consul_download_dir}}/{{consul_download_file}}
  when: consul_download_stat.stat.exists == False
  
- name: extract latest consul version
  unarchive: >
    src={{consul_download_dir}}/{{consul_download_file}}
    dest={{consul_install_dir}}
    copy=no
    owner={{consul_user}}
    group={{consul_group}}
    
- name: ensure consul executables have x bit set
  file: >
    state=file
    path={{consul_install_dir}}/{{item}}
    mode=0755
  with_items:
    - consul
    
- name: register the systemd service
  template: src=systemd.service dest=/etc/systemd/system/consul.service
  
- name: register consul on path using profile.d
  template: src=profiled.sh dest=/etc/profile.d/consul.sh
  
- name: configure consul
  template: "src=consul.json dest={{consul_config_dir}}/config.json"
  
- name: configure firewall for consul
  firewalld: "port={{item}} permanent=yes state=enabled immediate=yes"
  with_items:
    - "{{consul_port_server}}/tcp"
    - "{{consul_port_serf_lan}}/tcp"
    - "{{consul_port_serf_wan}}/tcp"