---
- name: install dnsmasq
  yum: name=dnsmasq state=present
  
- name: ensure required directories are available
  file: "state=directory path="
  with_items:
    - /etc/dnsmasq.d
    - /etc/resolveconf/resolv.conf.d
  
- name: configure dnsmasq to load configs from folder
  lineinfile: >
    dest=/etc/dnsmasq.conf
    regexp="^#conf-dir=/etc/dnsmasq.conf"
    line="conf-dir=/etc/dnsmasq.d
    state=present
    
- name: configure resolve to lookup on localhost
  lineinfile: >
    line="nameserver 127.0.0.1"
    insertbefore=BOF
    state=present
    dest={{item}}
    create=yes
  with_items:
    - /etc/resolveconf/resolv.conf.d/consul
    - /etc/resolv.conf
    
- name: configure sysconfig network to use local dns server
  lineinfile: line="DNS1=127.0.0.1 insertbefore=BOF state=present dest=/etc/sysconfig/network
  
- name: configure dnsmasq to only listen on lo
  lineinfile: >
    dest=/etc/dnsmasq.conf
    regexp: "^#interface="
    line: "interface=lo"
  notify: restart dnsmasq
    
- name: disable DHCP and TFTP functionality
  lineinfile: >
    dest=/etc/dnsmasq.conf
    regexp="^#no-dhcp-interface="
    line="no-dhcp-interface=lo"
  notify: restart dnsmasq
    
- name: forward all DNS masq requests to consul
  copy: >
    dest=/etc/dnsmasq.d/10-consul
    content='server=/{{ consul_domain }}/{{ 127.0.0.1 }}#{{ consul_port_dns }}
  notify: restart dnsmasq
  
- name: start dnsmasq service
  service: name=dnsmasq state=running enable=yes