---
nginx_package_url: http://nginx.org/packages/mainline/centos/7/$basearch/

nginx_default_sites:
 - default.conf
 - example_ssl.conf
 
http_port: 80
https_port: 443
 
nginx_ports:
 - "{{http_port}}/tcp"
 - "{{https_port}}/tcp"
 
nginx_dhparam: /etc/nginx/ssl/dhparam.pem